[package]
name = "hypertok-prebuilt-fixture"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hypertok = { path = "../../..", default-features = false, features = ["htk", "portable-json", "opt-prebuilt-pair-ranks"] }
hypertok-converter = { path = "../../../hypertok-converter" }
hypertok-format = { path = "../../../hypertok-format" }

[workspace]
